#!/bin/sh

################################################################################
# DESCRIPTON : ********
# MAINTAINER : ********   
# DATE       : ********
################################################################################
# set -eou pipefail

export DEFAULT_KUBECONFIG_PATH="$HOME/.kube/config"
export MAIN_FREENS_FOLDER="/tmp/freens"
export SHELL_PID="$PPID"
export FREENS_CONTEXT_PATH="${MAIN_FREENS_FOLDER}/${SHELL_PID}"
export NUMBER_OF_ARGS="$#"


### INFO MESSAGE ###
_info() {
    printf "$*"
}

### FAIL MESSAGE ###
_fail() {
    printf "\nERROR: $*\n"
    exit 1
}

#######################################
# 
# Globals:
    # 

# Arguments:
#   None
#######################################
get_kubeconfig_path() {
    if [[ -n "${KUBECONFIG}" ]]; then
        _info "${KUBECONFIG}"
    elif [[ -f "${DEFAULT_KUBECONFIG_PATH}" ]]; then
        _info "${DEFAULT_KUBECONFIG_PATH}"
    else
        _fail "There is no avaliable kube config file!"
    fi
    
}

#######################################
# 
# Globals:
    # 
# Arguments:
#   None
#######################################
create_freens_context_folder() {
    mkdir -pv "$FREENS_CONTEXT_PATH" > /dev/null 2>&1
}

#######################################
# 
# Globals:
    # 
# Arguments:
#   None
#######################################
create_freens_config_file() {
     _CURRENT_CONFIG_FILE=$1
    cp "${_CURRENT_CONFIG_FILE}" "${FREENS_CONTEXT_PATH}/config" > /dev/null 2>&1 || :
}

#######################################
# 
# Globals:
    # 
# Arguments:
#   None
#######################################
set_freens_config() {
    export KUBECONFIG="${FREENS_CONTEXT_PATH}/config"
    _info "This shell is free now..."
}


#######################################
# 
# Globals:
    # 
# Arguments:
#   None
#######################################
cleanup_freens_configs() {

    for dir in $(find "$MAIN_FREENS_FOLDER" -mindepth 1 -type d); do
        # Extract the PID from the directory name
        pid=$(basename "$dir")
        
        # Check if the PID corresponds to an active process
        if ps -p "$pid" > /dev/null; then
            :
        else
            rm -rf "${MAIN_FREENS_FOLDER}/${pid}"
        fi
    done

}

#######################################
# ~MARK: Usage of script
#######################################
usage() {
    cat <<EOF
        
        USAGE: 
            $ source freens

        DESCRIPTION: Will be filled
      
EOF
    exit 1
}

#######################################
# ~MARK: Main function
#######################################
main(){
    [ "$NUMBER_OF_ARGS" -ge 1 ] && usage && exit 0
    KUBECONFIG_PATH=$(get_kubeconfig_path)
    create_freens_context_folder
    create_freens_config_file "$KUBECONFIG_PATH"
    set_freens_config
    cleanup_freens_configs
}

# [[ "$0" == "$BASH_SOURCE" ]] && main "$@"
main