#!/bin/sh

################################################################################
# DESCRIPTON : ********
# MAINTAINER : ********   
# DATE       : ********
################################################################################
# set -eou pipefail

export DEFAULT_KUBECONFIG_PATH="$HOME/.kube/config"
export MAIN_FREENS_FOLDER="/tmp/freens"
export SHELL_PID="$PPID"
export FREENS_CONTEXT_PATH="${MAIN_FREENS_FOLDER}/${SHELL_PID}"


### INFO MESSAGE ###
_info() {
    echo "$@"
}

### FAIL MESSAGE ###
_fail() {
    echo -e "\nERROR: $@\n"
    exit 1
}

get_kubeconfig_path() {
    if [[ -n "${KUBECONFIG}" ]]; then
        _info "${KUBECONFIG}"
    elif [[ -f "${DEFAULT_KUBECONFIG_PATH}" ]]; then
        _info "${DEFAULT_KUBECONFIG_PATH}"
    else
        _fail "There is no avaliable kube config file!"
    fi
    
}

create_freens_context_folder() {
    mkdir -pv "$FREENS_CONTEXT_PATH" > /dev/null 2>&1
}

create_freens_config_file() {
    local CURRENT_CONFIG_FILE=$1
    cp $CURRENT_CONFIG_FILE "${FREENS_CONTEXT_PATH}/config" > /dev/null 2>&1 || :
}

set_freens_config() {
    export KUBECONFIG="${FREENS_CONTEXT_PATH}/config"
    _info "This shell is free now..."
}

cleanup_freens_configs() {

    for dir in $(find "$MAIN_FREENS_FOLDER" -mindepth 1 -type d); do
        # Extract the PID from the directory name
        pid=$(basename "$dir")
        
        # Check if the PID corresponds to an active process
        if ps -p "$pid" > /dev/null; then
            :
        else
            rm -rf "${MAIN_FREENS_FOLDER}/${pid}"
        fi
    done

}

#######################################
# ~MARK: Main function
#######################################
main(){
    KUBECONFIG_PATH=$(get_kubeconfig_path)
    create_freens_context_folder
    create_freens_config_file "$KUBECONFIG_PATH"
    set_freens_config
    cleanup_freens_configs
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"